export const $previewImage = $('#userimage .inner').installBackgroundImageExtend();
export const $coverImage = $('#coverimage .inner');
export const $dragImage = $('#dragger').installDivExtend();
export const $slider = $('#size-slider');
export const $loading = $('#loading');
export const $uploading = $('#uploading');
export const $submit = $("#normalSubmit");
export const $download = $('#download');
export const $drop = $('#drop');
